# Generated by Django 5.0.6 on 2024-06-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("school_name", models.CharField(max_length=500)),
                (
                    "school_address",
                    models.CharField(default=None, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "school_profile_info",
            },
        ),
        migrations.CreateModel(
            name="StateProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "state_profile_info",
            },
        ),
        migrations.CreateModel(
            name="SubjectProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("subject_name", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "subject_profile_info",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=400, null=True)),
                ("state", models.CharField(max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school_id",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UploadAPP.schoolprofile",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UploadAPP.subjectprofile",
                    ),
                ),
            ],
            options={
                "db_table": "student_profile_info",
            },
        ),
    ]
