# Generated by Django 5.0.6 on 2024-06-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UploadAPP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=500)),
                ("country_code", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "db_table": "country_profile",
            },
        ),
        migrations.RemoveField(
            model_name="stateprofile",
            name="country",
        ),
        migrations.AddField(
            model_name="stateprofile",
            name="country_id",
            field=models.ForeignKey(
                db_column="country_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UploadAPP.countryprofile",
            ),
        ),
    ]
