# Generated by Django 5.0.6 on 2024-06-03 13:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UploadAPP", "0002_countryprofile_remove_stateprofile_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVMetaData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "upload_csv_meta_data",
            },
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="csv_id",
            field=models.ForeignKey(
                db_column="csv_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UploadAPP.csvmetadata",
            ),
        ),
    ]
