# Generated by Django 5.0.6 on 2024-06-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UploadAPP", "0003_csvmetadata_studentprofile_csv_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="state",
        ),
        migrations.AddField(
            model_name="stateprofile",
            name="state_code",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="state_id",
            field=models.ForeignKey(
                db_column="state_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UploadAPP.stateprofile",
            ),
        ),
    ]
